---
deployment:
      tasks:
        - export DEPLOYPATH=/home/ws6gs9ua9bm3/fastlinky.com  # Add /<app_folder> if required
        - /bin cp * $DEPLOYPATH                           #copy all from root 
        - /bin cp /fastlinky.com/* $DEPLOYPATH             #copy all from sub folder root
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH